# -*- coding: utf-8 -*-
"""
OBJ Writer for GEM-AI geometry export.
Generates Wavefront OBJ files for 3D visualization.
"""

from __future__ import annotations

from typing import List, Tuple
from .geometry_extractor import ExtractedGeometry, DetectedRoom


class OBJWriter:
    """
    Generates Wavefront OBJ files from extracted geometry.

    Creates simple box geometries for each room that can be
    visualized in 3D viewers like Three.js.
    """

    def __init__(self):
        self.vertices: List[Tuple[float, float, float]] = []
        self.faces: List[List[int]] = []
        self.vertex_offset = 0

    def from_extracted_geometry(
        self,
        geometry: ExtractedGeometry,
        floor_z: float = 0.0,
    ) -> 'OBJWriter':
        """
        Create OBJ geometry from extracted geometry.

        Args:
            geometry: ExtractedGeometry with room data
            floor_z: Z-coordinate for floor level (default: 0.0)

        Returns:
            Self for method chaining
        """
        for room in geometry.rooms:
            self._add_room_box(
                x=room.x,
                y=room.y,
                z=floor_z,
                width=room.width,
                depth=room.depth,
                height=room.height,
            )

        return self

    def _add_room_box(
        self,
        x: float,
        y: float,
        z: float,
        width: float,
        depth: float,
        height: float,
    ) -> None:
        """
        Add a box (room) to the geometry.

        Vertices are added in this order:
        - 4 vertices for bottom face (z)
        - 4 vertices for top face (z + height)
        """
        # Bottom face vertices (counter-clockwise when viewed from top)
        v0 = (x, y, z)
        v1 = (x + width, y, z)
        v2 = (x + width, y + depth, z)
        v3 = (x, y + depth, z)

        # Top face vertices
        v4 = (x, y, z + height)
        v5 = (x + width, y, z + height)
        v6 = (x + width, y + depth, z + height)
        v7 = (x, y + depth, z + height)

        # Add all 8 vertices
        base_idx = self.vertex_offset + 1  # OBJ uses 1-indexed vertices
        self.vertices.extend([v0, v1, v2, v3, v4, v5, v6, v7])

        # Add faces (quads)
        # Bottom face (looking up, counter-clockwise)
        self.faces.append([base_idx, base_idx + 1, base_idx + 2, base_idx + 3])

        # Top face (looking down, counter-clockwise)
        self.faces.append([base_idx + 4, base_idx + 7, base_idx + 6, base_idx + 5])

        # Side faces (counter-clockwise when viewed from outside)
        # Front face (y = 0)
        self.faces.append([base_idx, base_idx + 4, base_idx + 5, base_idx + 1])

        # Right face (x = width)
        self.faces.append([base_idx + 1, base_idx + 5, base_idx + 6, base_idx + 2])

        # Back face (y = depth)
        self.faces.append([base_idx + 2, base_idx + 6, base_idx + 7, base_idx + 3])

        # Left face (x = 0)
        self.faces.append([base_idx + 3, base_idx + 7, base_idx + 4, base_idx])

        self.vertex_offset += 8

    def generate(self) -> str:
        """
        Generate OBJ file content as a string.

        Returns:
            OBJ format string
        """
        lines = [
            "# Generated by GEM-AI",
            "# Wavefront OBJ file",
            "",
        ]

        # Write vertices
        for v in self.vertices:
            lines.append(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}")

        lines.append("")

        # Write faces
        for face in self.faces:
            face_str = " ".join(str(idx) for idx in face)
            lines.append(f"f {face_str}")

        return "\n".join(lines)

    def save(self, filename: str) -> None:
        """
        Save OBJ file to disk.

        Args:
            filename: Path to save the OBJ file
        """
        content = self.generate()
        with open(filename, 'w') as f:
            f.write(content)
